[project]
name = "coqui-imp"
version = "0.1.0"
description = ""
authors = [
	{ name = "Cammy", email = "cameronsteele@steelecameron.com" }
]
readme = "README.md"
dependencies = [
	"python >=3.10,<3.11",
	"tts >=0.13.3",
	"playsound >= ^1.3.0",
]
